---
name: hello
userdata:
  type: local
  path: examples/scripts/userdata.sh

tags:
  - project=test
  - repo=hello-deploy

stacks:
  - stack: artd
    polling_interval: 30s
    account: dev
    env: dev
    replacement_type: DeployOnly
    ebs_optimized: true
    block_devices:
      - device_name: /dev/xvda
        volume_size: 8
        volume_type: "gp3"
    capacity:
      min: 1
      max: 1
      desired: 1

    regions:
      - region: ap-northeast-2
        instance_type: t3.medium
        ssh_key: test-master-key
        ami_id: ami-01288945bd24ed49a
        use_public_subnets: true
        vpc: vpc-artd_apnortheast2
        detailed_monitoring_enabled: false
        security_groups:
          - default-artd_apnortheast2
        availability_zones:
          - ap-northeast-2a
          - ap-northeast-2b
          - ap-northeast-2c
