---
name: hello
userdata:
  type: local
  path: examples/scripts/userdata.sh

autoscaling: &autoscaling_policy
  - name: scale_out
    adjustment_type: ChangeInCapacity
    scaling_adjustment: 1
    cooldown: 60
  - name: scale_in
    adjustment_type: ChangeInCapacity
    scaling_adjustment: -1
    cooldown: 180

alarms: &autoscaling_alarms
  - name: scale_out_on_util
    namespace: AWS/EC2
    metric: CPUUtilization
    statistic: Average
    comparison: GreaterThanOrEqualToThreshold
    threshold: 50
    period: 120
    evaluation_periods: 2
    alarm_actions:
      - scale_out
  - name: scale_in_on_util
    namespace: AWS/EC2
    metric: CPUUtilization
    statistic: Average
    comparison: LessThanOrEqualToThreshold
    threshold: 30
    period: 300
    evaluation_periods: 3
    alarm_actions:
      - scale_in

tags:
  - project=test
  - repo=hello-deploy

stacks:
  - stack: artd
    polling_interval: 30s
    account: dev
    env: dev
    assume_role: ""
    replacement_type: BlueGreen
    iam_instance_profile: 'app-hello-profile'
    ebs_optimized: true
    block_devices:
      - device_name: /dev/xvda
        volume_size: 10
        volume_type: "gp2"
      - device_name: /dev/xvdb
        volume_type: "st1"
        volume_size: 500
    capacity:
      min: 1
      max: 2
      desired: 1
    autoscaling: *autoscaling_policy
    alarms: *autoscaling_alarms
    lifecycle_callbacks:
      pre_terminate_past_cluster:
        - service hello stop

    regions:
      - region: ap-northeast-2
        instance_type: t3.medium
        ssh_key: test-master-key
        ami_id: ami-01288945bd24ed49a
        use_public_subnets: true
        vpc: vpc-artd_apnortheast2
        detailed_monitoring_enabled: false
        security_groups:
          - hello-artd_apnortheast2
          - default-artd_apnortheast2

        # This should be a classic load balancer
        healthcheck_load_balancer: test
        availability_zones:
          - ap-northeast-2a
          - ap-northeast-2b
          - ap-northeast-2c
