---
name: hello
replacement_type: BlueGreen

autoscaling: &autoscaling_policy
  scale_up:
    adjustment_type: ChangeInCapacity
    scaling_adjustment: 1
    cooldown: 60
  scale_down:
    adjustment_type: ChangeInCapacity
    scaling_adjustment: -1
    cooldown: 180

alarms: &autoscaling_alarms
  scale_up_on_util:
    namespace: AWS/EC2
    metric: CPUUtilization
    statistic: Average
    comparison: GreaterThanOrEqualToThreshold
    threshold: 50
    period: 120
    evaluation_periods: 2
    alarm_actions:
      - scale_up
  scale_down_on_util:
    namespace: AWS/EC2
    metric: CPUUtilization
    statistic: Average
    comparison: LessThanOrEqualToThreshold
    threshold: 30
    period: 300
    evaluation_periods: 3
    alarm_actions:
      - scale_down

tags:
  project: test
  app: hello
  repo: hello-deploy

environments:
  - stack: dayonep
    account: prod
    instance_type: t3.large
    ssh_key: dayone-prod-master
    iam_instance_profile: 'app-hello-profile'
    ansible_tags: all
    extra_vars: ""
    block_devices:
      - device_name: /dev/xvda
        volume_size: 100
        volume_type: "gp2"
    capacity:
      min: 1
      max: 1
      desired: 1
    autoscaling:
      <<: *autoscaling_policy
    alarms:
      <<: *autoscaling_alarms
    lifecycle_callbacks:
      pre_terminate_past_clusters:
        - service hello stop
    regions:
      - region: ap-northeast-2
        vpc: vpc-dayonep_apnortheast2
        security_groups:
          - hello-dayonep_apnortheast2
          - default-dayonep_apnortheast2
        healthcheck_target_group: hello-dayonepapne2-ext
        target_groups:
          - hello-dayonepapne2-ext


